#!/usr/bin/env python3
"""Regenerate src/pitable.rs for reduce_pi_wide.

beta(e) = (2^(e-150)/pi) mod 2, so |x|/pi = m * beta(e) (mod 2) for the
24-bit integer mantissa m of a normal f32 with biased exponent e. Bit p of
beta(e) (weight 2^-p after the binary point of 1/pi) is bit p + e - 150 of
1/pi, so every row of a beta table is one window of a single bit string.

WORDS holds bits of 1/pi at positions CUT-150 .. CUT-150+255, big-endian in
u32 words; reduce_pi_wide reads 96 bits starting at position e-150 by word
select + funnel shift. Exact integer arithmetic via Machin's formula.
"""
import sys

S = 700
CUT = 115
NWORDS = 8

def arctan_inv(x, one):
    total = term = one // x
    x2 = x * x
    k = 3
    sign = -1
    while term != 0:
        term = term // x2
        total += sign * (term // k)
        sign = -sign
        k += 2
    return total

ONE = 1 << S
PI_S = 16 * arctan_inv(5, ONE) - 4 * arctan_inv(239, ONE)
INV_PI = (ONE * ONE) // PI_S  # floor(2^S / pi)

def bit(p):
    """Bit at position p (weight 2^-p) of 1/pi; zero for p <= 0."""
    return 0 if p <= 0 else (INV_PI >> (S - p)) & 1

base = CUT - 150
words = []
for i in range(NWORDS):
    w = 0
    for j in range(32):
        w = (w << 1) | bit(base + 32 * i + j)
    words.append(w)

# Self-check against the direct definition for every exponent the reduction reads.
for e in range(CUT, 256):
    t = e - CUT
    q, s = t >> 5, t & 31
    big = 0
    for i in range(q, q + 4):
        big = (big << 32) | words[i]
    window = (big >> (32 - s)) & ((1 << 96) - 1)
    num = 1 << (e - 150 + 95 + S)
    direct = (num // PI_S) % (1 << 96)
    exact = sum(bit(e - 150 + j) << (95 - j) for j in range(96))
    assert window == exact, e
    assert window == direct, e

src = f"""//! Bits of `1/pi` for `reduce_pi_wide`, generated by `tools/gen_pitable.py`
//! (edit that, not this).
//!
//! `WORDS` holds the bits at positions `CUT - 150 ..` (position `p` has weight
//! `2^-p`) big-endian, so the 96 bits of `(2^(e-150)/pi) mod 2` that matter
//! for biased exponent `e` start at bit `e - CUT` of the string.

pub(super) const CUT: u32 = {CUT};

pub(super) const WORDS: [u32; {NWORDS}] = [
    {", ".join(f"{w:#010x}" for w in words)},
];
"""
out = sys.argv[1] if len(sys.argv) > 1 else "src/pitable.rs"
open(out, "w").write(src)
print("wrote", out)
