//! Bits of `1/pi` for `reduce_pi_wide`, generated by `tools/gen_pitable.py`
//! (edit that, not this).
//!
//! `WORDS` holds the bits at positions `CUT - 150 ..` (position `p` has weight
//! `2^-p`) big-endian, so the 96 bits of `(2^(e-150)/pi) mod 2` that matter
//! for biased exponent `e` start at bit `e - CUT` of the string. Exponents
//! below `CUT` (|x| < 1) and 255 (inf/NaN) are not windowed.

pub(super) const CUT: u32 = 127;

pub(super) const WORDS: [u32; 7] = [
    0x00000051, 0x7cc1b727, 0x220a94fe, 0x13abe8fa, 0x9a6ee06d, 0xb14acc9e, 0x21c820ff,
];
